language: python
branches:
only:
  - master
python:
  - "2.7"
  #- "2.6"
  #
virtualenv:
  system_site_packages: true

before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq libgeos-3.2.2 libgeos-dev python-numpy python-scipy"
  - "sudo apt-add-repository 'deb http://us.archive.ubuntu.com/ubuntu/ raring main universe'"
  - "sudo apt-get update -qq"
  - "sudo apt-get --only-upgrade install -qq python-scipy"

install:
  - "pip install -q -r requirements.txt"
  - "sudo pip install http://sourceforge.net/projects/pychecker/files/pychecker/0.8.19/pychecker-0.8.19.tar.gz/download"
  #- "pip install coveralls"
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"

script: 
  - python -c 'import numpy; print numpy.version.version'
  - python -c 'import scipy; print scipy.version.version'
  - python setup.py install 
  - python -c 'import pysal; print pysal.version'
  #- pychecker --limit 1000 pysal
  - python setup.py sdist >/dev/null
  - nosetests 
  - cd doc; make pickle; make doctest
notifications:
    email:
        recipients:
            - pedrovma@gmail.com
        on_success: always
        on_failure: always
